language: c

os: 
    - osx
    - linux

sudo: required 

before_install:
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update; fi
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew install snaipe/soft/criterion; fi
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo add-apt-repository ppa:snaipewastaken/ppa -y; fi
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get update; fi
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo apt-get install criterion-dev; fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
